# Generated by Django 5.2.10 on 2026-01-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_acc', models.CharField(max_length=100)),
                ('cash', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
