# Generated by Django 5.2.10 on 2026-01-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testmodel',
            name='created_at',
        ),
    ]
